app = "poly-slimmer"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  PYTHONPATH = "/app"
  GLTFPACK_PATH = "/usr/local/bin/gltfpack"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[processes]
  web = "gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"
  worker = "python scripts/run_worker.py"

[mounts]
  destination = "/data"
  source = "data" 